routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//User
Route::group(['middleware' => ['role:admin']], function() {
    Route::resource('/user','userController');
    Route::get('/user/hapus/{id}','userController@destroy');
    Route::resource('/barang','BarangController');
    Route::get('/barang/hapus/{id}','barangController@destroy');
    Route::get('/barang/edit/{id}','BarangController@edit');
    Route::resource('/supplier','SupplierController')->middleware('role:admin');
    Route::get('/supplier/hapus/{id}','SupplierController@destroy');
    Route::get('/supplier/edit/{id}','SupplierController@edit');
    Route::resource('/akun', 'AkunController');
    Route::get('/akun/edit/{id}','AkunController@edit');
    Route::get('/akun/hapus/{id}','AkunController@destroy');
    Route::get('/setting','SettingController@index')->name('setting','transaksi')->middleware('role:admin');
    //Setting
    Route::get('/setting','SettingController@index')->name('setting.transaksi')->middleware('role:admin');
    Route::post('/setting/simpan','SettingController@simpan');
    //Pemesanan
    Route::get('/transaksi', 'PemesananController@index')->name('pemesanan.transaksi');
    Route::post('/sem/store', 'PemesananController@store');
    Route::get('/transaksi/hapus/{kd_brg}','PemesananController@destroy');
    //Detail Pesan
    Route::post('/detail/store', 'DetailPesanController@store');
    Route::post('/detail/simpan', 'DetailPesanController@simpan');
    Route::get('/pembelian', 'PembelianController@index')->name('pembelian.transaksi');
    Route::get('/pembelian-beli/{id}', 'PembelianController@edit');
    Route::post('/pembelian/simpan', 'PembelianController@simpan');
    //Retur 
    Route::get('/retur','ReturController@index')->name('retur.transaksi');
    Route::get('/retur-beli/{id}', 'ReturController@edit');
    Route::post('/retur/simpan', 'ReturController@simpan');
    //Laporan
    Route::resource( '/laporan' , 'LaporanController');
    Route::resource( '/stok' , 'LapStokController');
    Route::get('/laporan/faktur/{invoice}', 'PembelianController@pdf')->name('cetak.order_pdf');
    //laporan cetak
    Route::get('/laporancetak/cetak_pdf', 'LaporanController@cetak_pdf');
            
});

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    //jika tidak di definisikan, maka primary akan terdetek id_supp
    protected $primarykey = 'id';
    public $incrementing = false;
    protected $keytype = 'string';
    public $timestamps = false;
    protected $table = "supplier";
    protected $fillable=['id', 'nm_supp', 'alamat', 'telepon'];
}

app/Http/Controllers/supplierController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Alert;
use App\supplier;
class SupplierController extends Controller
{
public function index()
    {
        $supplier=\App\Supplier::All();
        return view('admin.supplier.supplier',['supplier'=>$supplier]);
    }
public function create()
    {
        $supp = new \App\Supplier;
        $supp->id=$request->get('addid');
        $supp->nm_supp=$request->get('addnmsup');
        $supp->alamat=$request->get('addalamat');
        $supp->telepon=$request->get('addtelepon');
        return redirect('/supplier');
    }
 public function store(Request $request)
    {
        $save_supplier = new \App\Supplier;
        $save_supplier->id=$request->get('addid');
        $save_supplier->nm_supp=$request->get('addnmsup');
        $save_supplier->alamat=$request->get('addalamat');
        $save_supplier->telepon=$request->get('addtelepon');
        $save_supplier->save();
        return redirect('/supplier');
    }
public function edit($id)
    {
        $supp_edit = \App\Supplier::findOrFail($id);
        return view( 'admin.editSupplier' , ['supplier' => $supp_edit]);
    }

public function update(Request $request, $id)
    {
        $update_supp = \App\Supplier::findOrFail($id);
        $update_supp->id=$request->get('addid');
        $update_supp->nm_supp=$request->get('addnmsupp');
        $update_supp->alamat=$request->get('addalamat');
        $update_supp->telepon=$request->get('addtelepon');
        $update_supp->save();
        //------------- OR you can simply do ---------------------------//

        //$update_supplier = id::findOrFail($id);

        //$update_supplier->update($request->all();

    //-------------------------------------------------------------//
        Alert::success('update', 'Data Berhasil Diupdate');
        return redirect()->route( 'supplier.index');
    }

public function destroy($id)
    {
        $supp=\App\Supplier::findOrFail($id);
        $supp->delete();
        Alert::success('Pesan ','Data berhasil dihapus');
        return redirect()->route('supplier.index');
    }
}

resources/views/admin/supplier/supplier.blade.php
@extends('layouts.layout')
@section('content')
@include('sweetalert::alert')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
 <h1 class="h3 mb-0 text-gray-800">Data Supplier</h1>
 </div>
<hr>
<div class="card-header py-3" align="right">
<button type="button" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" data-toggle="modal" data-target="#exampleModalScrollable">
<i class="fas fa-plus fa-sm text-white-50"></i> Tambah
</button>
</div>
<div class="d-sm-flex align-items-center justify-content-between mb-4">
<div class="card-body">
<div class="table-responsive">
<table class="table table-bordered table-striped" id="dataTable" width="100%" cellspacing="0">
 <thead class="thead-dark">
 <tr>
 <th>Kode Supplier</th>
 <th>Nama Supplier</th>
 <th>Alamat</th>
 <th>Telepon</th>
 <th>Aksi</th>
 </tr>
 </thead>
 <tbody>
 @foreach($supplier as $supp)
 <tr>
 <td>{{ $supp->id}}</td>
 <td>{{ $supp->nm_supp}}</td>
 <td>{{ $supp->alamat}}</td>
 <td>{{ $supp->telepon}}</td>
 <td align="center">
 <a href="{{route('supplier.edit',[$supp->id])}}"class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm">
 <i class="fas fa-edit fa-sm text-white-50"></i> Edit</a>

 <a href="/supplier/hapus/{{$supp->id}}" onclick="return confirm('Yakin Ingin menghapus data?')" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm">
 <i class="fas fa-trash-alt fa-sm text-white-50"></i> Hapus</a>
 </td>
 </tr>
 @endforeach
 </tbody>
 </table>
</div>
</div>
</div>
<div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" ariahidden="true">
 <div class="modal-dialog modal-dialog-scrollable" role="document">
 <div class="modal-content">
 <div class="modal-header">
 <h5 class="modal-title" id="exampleModalScrollableTitle">Tambah Data Barang</h5>
 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
<span aria-hidden="true">&times;</span>
 </button>
 </div>
 <form action="{{ action('SupplierController@store') }}" method="POST">
 @csrf
 <div class="modal-body">
 <div class="form-group">
 <label for="exampleFormControlInput1">Kode Supplier</label>
 <input type="text" name="addid" id="addid" class="form-control" maxlegth="8" id="exampleFormControlInput1" >
 <div class="form-group">
 <label for="exampleFormControlInput1">Nama Supplier</label>
 <input type="text" name="addnmsupp" id="addnmsupp" class="form-control" id="exampleFormControlInput1" >

 <div class="form-group">
 <label for="exampleFormControlInput1">Alamat</label>
 <input type="text" name="addalamat" id="addalamat" class="form-control" id="exampleFormControlInput1" >
 
 <div class="form-group">
 <label for="exampleFormControlInput1">Telepon</label>
 <input type="number" name="addtelepon" id="addtelepon" class="form-control" id="exampleFormControlInput1" >
 
 </div>
 <div class="modal-footer">
 <button type="button" class="btn btn-secondary" data-dismiss="modal"> Batal</button>
 <input type="submit" class="btn btn-primary btn-send" value="Simpan">
 </div>
 </div>
 </form>
 </div>
</div>
@endsection