routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//User
Route::group(['middleware' => ['role:admin']], function() {
    Route::resource('/user','userController');
    Route::get('/user/hapus/{id}','userController@destroy');
    Route::resource('/barang','BarangController');
    Route::get('/barang/hapus/{id}','barangController@destroy');
    Route::get('/barang/edit/{id}','BarangController@edit');
    Route::resource('/supplier','SupplierController')->middleware('role:admin');
    Route::get('/supplier/hapus/{id}','SupplierController@destroy');
    Route::get('/supplier/edit/{id}','SupplierController@edit');
    Route::resource('/akun', 'AkunController');
    Route::get('/akun/edit/{id}','AkunController@edit');
    Route::get('/akun/hapus/{id}','AkunController@destroy');
    Route::get('/setting','SettingController@index')->name('setting','transaksi')->middleware('role:admin');
    //Setting
    Route::get('/setting','SettingController@index')->name('setting.transaksi')->middleware('role:admin');
    Route::post('/setting/simpan','SettingController@simpan');
    //Pemesanan
    Route::get('/transaksi', 'PemesananController@index')->name('pemesanan.transaksi');
    Route::post('/sem/store', 'PemesananController@store');
    Route::get('/transaksi/hapus/{kd_brg}','PemesananController@destroy');
    //Detail Pesan
    Route::post('/detail/store', 'DetailPesanController@store');
    Route::post('/detail/simpan', 'DetailPesanController@simpan');
    Route::get('/pembelian', 'PembelianController@index')->name('pembelian.transaksi');
    Route::get('/pembelian-beli/{id}', 'PembelianController@edit');
    Route::post('/pembelian/simpan', 'PembelianController@simpan');
    //Retur 
    Route::get('/retur','ReturController@index')->name('retur.transaksi');
    Route::get('/retur-beli/{id}', 'ReturController@edit');
    Route::post('/retur/simpan', 'ReturController@simpan');
    //Laporan
    Route::resource( '/laporan' , 'LaporanController');
    Route::resource( '/stok' , 'LapStokController');
    Route::get('/laporan/faktur/{invoice}', 'PembelianController@pdf')->name('cetak.order_pdf');
    //laporan cetak
    Route::get('/laporancetak/cetak_pdf', 'LaporanController@cetak_pdf');
            
});

resources/views/admin/editBarang.blade.php
@extends('layouts.layout')
@section('content')
@include('sweetalert::alert')
<form action="{{route('barang.update', [$barang->kd_brg])}}" method="POST">
 @csrf
 <input type="hidden" name="_method" value="PUT">
 <fieldset>
 <legend>Ubah Data Barang</legend>
 <div class="form-group row">
 <div class="col-md-5">
 <label for="addkdbrg">Kode Barang</label>
 <input class="form-control" type="text" name="addkdbrg" value="{{$barang->kd_brg}}" readonly>
 </div>
 <div class="col-md-5">
 <label for="addnmbrg">Nama Barang</label>
 <input id="addnmbrg" type="text" name="addnmbrg" class="form-control" value="{{$barang->nm_brg}}">
 </div>
 <div class="col-md-5">
 <label for="Harga">Harga</label>
 <input id="addharga" type="text" name="addharga" class="form-control" value="{{$barang->harga}}">
 </div>
 <div class="col-md-5">
 <label for="Stok">Stok</label>
 <input id="addstok" type="text" name="addstok" class="form-control" value="{{$barang->stok}}">
 </div>
 </fieldset>
 <div class="col-md-10">
 <input type="submit" class="btn btn-success btn-send" value="Update">
 <a href="{{ route('barang.index') }}"><input type="Button" class="btn btn-primary btn-send" value="Kembali"></a>
 </div>
 <hr>
</form>
@endsection

resources/views/admin/editSupplier.blade.php
@extends('layouts.layout')
@section('content')
@include('sweetalert::alert')
<form action="{{route('supplier.update', [$supplier->id])}}" method="POST">
 @csrf
 <input type="hidden" name="_method" value="PUT">
 <fieldset>
 <legend>Ubah Data Supplier</legend>
 <div class="form-group row">
 <div class="col-md-5">
 <label for="addid">Kode Supplier</label>
 <input class="form-control" type="text" name="addid" value="{{$supplier->id}}" readonly>
 </div>
 <div class="col-md-5">
 <label for="addnmsupp">Nama Supplier</label>
 <input id="addnmsupp" type="text" name="addnmsupp" class="form-control" value="{{$supplier->nm_supp}}">
 </div>
 <div class="col-md-5">
 <label for="Alamat">Alamat</label>
 <input id="addalamat" type="text" name="addalamat" class="form-control" value="{{$supplier->alamat}}">
 </div>
 <div class="col-md-5">
 <label for="telepon">No Telepon</label>
 <input id="addtelepon" type="text" name="addtelepon" class="form-control" value="{{$supplier->telepon}}">
 </div>
 </fieldset>
 <div class="col-md-10">
 <input type="submit" class="btn btn-success btn-send" value="Update">
 <a href="{{ route('supplier.index') }}"><input type="Button" class="btn btn-primary btn-send" value="Kembali"></a>
 </div>
 <hr>
</form>
@endsection

resources/views/admin/user.blade.php
@extends('layouts.layout')
@section('content') 
@include('sweetalert::alert')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
 <h1 class="h3 mb-0 text-gray-800">Data Pengguna</h1>
</div><hr>
<div class="card-header py-3" align="right"> 
 <button class="btn btn-primary btn-sm btn-flat" data-toggle="modal" data-target="#modal-add"><iclass="fa fa-plus"></i>Tambah</button>
</div>
<div class="d-sm-flex align-items-center justify-content-between mb-4"> 
 <div class="card-body">
 <div class="table-responsive">
 <table class="table tablebordered" id="dataTable" width="100%" cellspacing="0">
 <thead>
 <tr align="center">
 <th width="10%">User Id</th>
 <th width="25%">Nama</th>
 <th width="20%">Email</th>
 <th width="15%">Roles/Akses</th>
 <th width="25%">Aksi</th>
 </tr>
 </thead>
 <tbody>
 @foreach ($user as $row)
 <tr>
 <td>{{$row->username}}</td>
 <td>{{$row->name}}</td>
 <td>{{$row->email}}</td>  
 <td>{{$row->akses}}</td>
 </td>
 @foreach ($row->roles as $r) 
    {{$r->id}}
 </td> 
 @endforeach
 <td align="center">
 <a href="{{route( 'user.edit' ,[$row->id])}}" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm">
 <i class="fas fa-edit fa-sm text-white-50"></i> Edit
 <a href="/user/hapus/{{ $row->id }}" onclick="return confirm('Yakin Ingin menghapus data?')" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm">
 <i class="fas fa-trash-alt fa-sm text-white-50"></i> Hapus
 </a>
 </td>
 </tr>
 @endforeach
 </tbody>
 </table>
 </div>
 </div>
</div>
<!-- modal add data-->
<div class="modal inmodal fade" id="modal-add" tabindex="-1" role="dialog" aria-hidden="true">
 <div class="modal-dialog modal-xs">
 <form name="frm_add" id="frm_add" class="form-horizontal" action="#" method="POST"
 enctype="multipart/form-data">
 @csrf
 <div class="modal-content">
 <div class="modal-header">
 <h4 class="modal-title">Tambah Data User</h4>
 </div>
 <div class="modal-body">
 <div class="form-group"><label class="col-lg-20 control-label">Nama User</label>
 <div class="col-lg-10"><input type="text" name="username" required
 class="form-control"></div>
 <div class="form-group"><label class="col-lg-20 control-label">Email User</label>
 <div class="col-lg-10"><input type="email" name="email" required
 class="form-control"></div>
 <div class="form-group"><label class="col-lg-20 control-label">Roles/Akses</label>
 <div class="col-lg-10">
 <select id="roles" name="roles" class="form-control" required>
 <option value="">--Pilih Roles--</option>
 <option value="ADMIN">Admin</option>
 <option value="USER">User</option>
 </select>
 </div>
</div>
 </div>
 <div class="modal-footer">
 <button type="button" class="btn btn-light" data-dismiss="modal">Tutup</button>
 <button type="submit" class="btn btn-primary">Simpan</button>
 </div>
@endsection
 </div>
 </form>
 </div>
</div>