routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//User
Route::group(['middleware' => ['role:admin']], function() {
    Route::resource('/user','userController');
    Route::get('/user/hapus/{id}','userController@destroy');
    Route::resource('/barang','BarangController');
    Route::get('/barang/hapus/{id}','barangController@destroy');
    Route::get('/barang/edit/{id}','BarangController@edit');
    Route::resource('/supplier','SupplierController')->middleware('role:admin');
    Route::get('/supplier/hapus/{id}','SupplierController@destroy');
    Route::get('/supplier/edit/{id}','SupplierController@edit');
    Route::resource('/akun', 'AkunController');
    Route::get('/akun/edit/{id}','AkunController@edit');
    Route::get('/akun/hapus/{id}','AkunController@destroy');
    Route::get('/setting','SettingController@index')->name('setting','transaksi')->middleware('role:admin');
    //Setting
    Route::get('/setting','SettingController@index')->name('setting.transaksi')->middleware('role:admin');
    Route::post('/setting/simpan','SettingController@simpan');
    //Pemesanan
    Route::get('/transaksi', 'PemesananController@index')->name('pemesanan.transaksi');
    Route::post('/sem/store', 'PemesananController@store');
    Route::get('/transaksi/hapus/{kd_brg}','PemesananController@destroy');
    //Detail Pesan
    Route::post('/detail/store', 'DetailPesanController@store');
    Route::post('/detail/simpan', 'DetailPesanController@simpan');
    Route::get('/pembelian', 'PembelianController@index')->name('pembelian.transaksi');
    Route::get('/pembelian-beli/{id}', 'PembelianController@edit');
    Route::post('/pembelian/simpan', 'PembelianController@simpan');
    //Retur 
    Route::get('/retur','ReturController@index')->name('retur.transaksi');
    Route::get('/retur-beli/{id}', 'ReturController@edit');
    Route::post('/retur/simpan', 'ReturController@simpan');
    //Laporan
    Route::resource( '/laporan' , 'LaporanController');
    Route::resource( '/stok' , 'LapStokController');
    Route::get('/laporan/faktur/{invoice}', 'PembelianController@pdf')->name('cetak.order_pdf');
    //laporan cetak
    Route::get('/laporancetak/cetak_pdf', 'LaporanController@cetak_pdf');
            
});

app/Akun.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Akun extends Model
{
    protected $primaryKey = 'no_akun';
    public $incrementing = false;
    protected $keyType = 'string';
    public $timestamps = false;
    protected $table = "akun";
    protected $fillable=['no_akun','nama_akun'];
}

app/Http/Controllers/AkunController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AkunController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $akun=\App\Akun::All();
        return view('admin.akun.akun',['akun'=>$akun]); //Array
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.akun.input');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //untuk menyimpan data
        $tambah_akun=new \App\Akun;
        $tambah_akun->no_akun = $request->addnoakun;
        $tambah_akun->nm_akun = $request->addnmakun;
        $tambah_akun->save(); // method
        return redirect('/akun'); // prosedur

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $update_akun = \App\akun::findOrFail($id);
        $update_akun->no_akun=$request->addnoakun;
        $update_akun->nm_akun=$request->addnmakun;
        $update_akun->save();
        Alert::success('Update', 'Data Berhasil di update');
        return redirect()->route( 'akun.index');
        $tambah_akun->no_akun = $request->addnoakun;

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $akun=\App\Akun::findOrFail($id);
        $akun->delete();
        return redirect()->route('akun.index');
            }
}

resources/views/admin/akun/akun.blade.php
@extends('layouts.layout')
@section('content')
@include('sweetalert::alert')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
 <h1 class="h3 mb-0 text-gray-800">Data Akun Rekening</h1>
</div>
<hr>
<div class="card-header py-3" align="right">
<button type="button" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" data-toggle="modal" data-target="#exampleModalScrollable">
<i class="fas fa-plus fa-sm text-white-50"></i> Tambah
</button>
</div>
<div class="d-sm-flex align-items-center justify-content-between mb-4">
<div class="card-body">
<div class="table-responsive">
<table class="table table-bordered tablestriped " id="dataTable" width="100%" cellspacing="0">
 <thead class="thead-dark">
 <tr>
 <th width="20%">KodeAkun</th>
 <th>NamaAkun</th>
 <th width="20%">Aksi</th>
 </tr>
 </thead>
 <tbody>
 @foreach($akun as $akn)
 <tr>
 <td>{{$akn->no_akun}}</td>
 <td>{{$akn->nm_akun}}</td>
 <td align="center"><a href="{{route('akun.edit',[$akn->no_akun])}}"class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm">
 <i class="fas fa-edit fa-sm text-white-50"></i> Edit</a>
 <a href="/akun/hapus/{{$akn->no_akun}}" onclick="return confirm('Yakin Ingin menghapus data?')" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm">
 <i class="fas fa-trash-alt fa-sm text-white-50"></i> Hapus</a>
 </td>
 </tr>
 @endforeach
 </tbody>
 </table>
</div>
</div>
</div>
<div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" ariahidden="true">
 <div class="modal-dialog modal-dialog-scrollable" role="document">
 <div class="modal-content">
 <div class="modal-header">
 <h5 class="modaltitle" id="exampleModalScrollableTitle">Tambah Data Akun</h5>
 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
 <span aria-hidden="true">&times;</span>
 </button>
 </div>
 <form action="{{ action('AkunController@store') }}" method="POST">
 @csrf
 <div class="modal-body">
 <div class="form-group">
 <label for="exampleFormControlInput1">Kode Akun</label>
 <input type="text" name="addnoakun" id="addnoakun" class="form-control" id="exampleFormControlInput1" >
 </div>
 <div class="form-group">
 <label for="exampleFormControlInput1">Nama Akun</label>
 <input type="text" name="addnmakun" id="addnmakun" class="form-control" id="exampleFormControlInput1" >
 </div>
 </div>
 <div class="modal-footer">
 <button type="button" class="btn btn-secondary" data-dismiss="modal"> Batal</button>
 <input type="submit" class="btn btn-primary btn-send" value="Simpan">
 </div>
 </div>
 </form>
 </div>
</div>
@endsection

resources/views/admin/akun/editakun.blade.php
@extends('layouts.layout')
@section('content')
<form action="{{route('akun.update',[$akun->no_akun])}}" method="POST">@csrf
<input type="hidden" name="_method" value="PUT">
<fieldset><legend>Rubah Form Data Akun</legend>
 <div class="form-group row">
 <div class="col-md-5">
 <label for="addnoakun">Kode Akun</label>
 <input id="addnoakun" type="text" name="addnoakun" class="form-control" value="{{$akun->no_akun}}">
 </div>
 <div class="col-md-5">
 <label for="addnmakun">Nama Akun</label>
 <input id="addnmakun" type="text" name="addnmakun" class="form-control" value="{{$akun->nm_akun}}"></div>
 </div>
 
 <div class="col-md-10">
 <input type="submit" class="btn btn-success btn-send" value="Update">
 <a href="{{ route('akun.index') }}"><input type="Button" class="btn btn-primary btn-send" value="Kembali"></a>
 </div>
 <hr>
</fieldset>
</form>
@endsection

resources/views/admin/akun/input.blade.php
@extends('layouts.layout')
@section('content')
<form action="{{route('akun.store')}}" method="POST">@csrf
 <fieldset><legend>Input Data Akun</legend>
 <div class="form-group row">
 <div class="col-md-5">
 <label for="usname">Kode Akun</label>
 <input id="usname" type="text" name="kodeakun" class="form-control"required>
 </div>
 <div class="col-md-5">
 <label for="nama">Nama Akun</label>
 <input id="nama" type="text" name="nama" class="form-control"required>
 </div>
 </div>
 <div class="col-md-10">
 <input type="submit" class="btn btn-success btn-send" value="Simpan">
 <input type="Button" class="btn btn-primary btnsend" value="Kembali" onclick="history.go(-1)">
 </div>
 <hr>
 </fieldset>
</form>
@endsection